version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    command: ["poetry", "run", "uvicorn", "backend_fastapi.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      DATABASE_URL: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data:
