version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - backend_fastapi/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    build:
      context: .  
      dockerfile: backend.dockerfile
    container_name: fastapi_app
    env_file:
      - backend_fastapi/.env
    command: ["poetry", "run", "uvicorn", "backend_fastapi.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  rendezvous_app:
    build:
      context: .
      dockerfile: frontend.dockerfile
    container_name: rendezvous_app
    env_file:
      - rendezvous_app/.env
    ports:
      - "3000:3000"
volumes:
  mysql_data:
