// Friend.js
import React from 'react';
import { Link } from 'react-router-dom';
const friendbtn = {
    margin: "10px 0",
    padding: "10px",
    backgroundColor: "#fff",
    color: "#000",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    width: "200px",
    justifyContent: "flex-start",
};

const avatarStyle = {
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    marginRight: "10px",
};

/** 
@typedef {Object} FriendProps
@property {string} username - The username of the friend.
@property {string} profile_image_src - The URL of the event image.
*/


/* Individual Friend Object
    Currently includes username and a sample image url. */
/**@param {FriendProps} props */
const Friend = ({ username, profile_image_src }) => {
    return (
        <button style={friendbtn} className="friend">
            <img src={profile_image_src} className="profile-image" alt="friend" style={avatarStyle} />
            <h2 className='username'>{username}</h2>
            {/* For now, profile_image_src will be fixed since the profile feature
            is still in development. In the next sprint, this will be a link to an image
            retrieved from the server. Additionally, a parameter will be added for a link
            to the friend's profile (generated by server from friend's username/id). */}
            <br />
        </button>
    );
};

export default Friend;
